version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  # Maintain dependencies for Python, supports pip, pipenv, pip-compile, and poetry
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
