[tox]
minversion = 3.3.0
envlist = py312

[testenv]
basepython=python3.12
ignore_basepython_conflict=true
deps =
    -c https://releases.openstack.org/constraints/upper/2025.1
    oslotest
    stestr
    python-openstackclient

commands =
    stestr run {posargs}

[testenv:pep8]
deps =
    ruff
commands =
    ruff check {posargs}
