[tox]
minversion = 3.3.0
envlist = py39

[testenv]
deps =
    -c https://releases.openstack.org/constraints/upper/2023.1
    oslotest
    stestr
    python-openstackclient

commands =
    stestr run {posargs}

[testenv:pep8]
deps =
    ruff
commands =
    ruff check {posargs}
