name: CI

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
  release:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12']
        linter: [false]
        include:
          - python-version: '3.8'
            linter: pep8
    steps:
      - name: Sets TOXENV to run linter
        run: |
          echo "TOXENV=pep8" >> $GITHUB_ENV
        if: startsWith( matrix.linter, 'pep8')
      - name: checkout source code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install tox tox-gh-actions
      - name: Run tests
        run: tox
